### ISSUE TITLE
Request better categorisation to have up to date list of Projects in scope for SIG Observability.

### ISSUE THREAD

**Issue by bwplotka** [cncf/sig-observability#10]
Tracking ticket to improve https://landscape.cncf.io/ to add some SIG-based label (: 

cc @caniszczyk  @idvoretskyi  :hugs: 

Will add JIRA issue for this.

**Comment by idvoretskyi** [comment]
@bwplotka if you have any enhancements in mind for the CNCF Landscape, you may submit a PR directly to https://github.com/cncf/landscape.

**Comment by bwplotka** [comment]
Ack :hugs:

**Comment by bwplotka** [comment]
Done: https://github.com/cncf/landscape/issues/1632

**Comment by bwplotka** [comment]
Looks like Dan had very good point: https://github.com/cncf/landscape/issues/1632#issuecomment-638763810 

Adding PR now.

**Comment by bwplotka** [comment]
Done (:
