### ISSUE TITLE
Prepare Incubation review for the Thanos project.

### ISSUE THREAD

**Issue by povilasv** [cncf/sig-observability#13]
Looks like we need a review from Sig Observability to move forward with Incubation stage for Thanos  https://github.com/cncf/toc/pull/342.

I'm also contacting Cortex people so we can maybe do Incubation stage together as the systems are quite similiar and due dilligence will have a lot in common.

Ref: https://github.com/cncf/sig-observability/issues/12 
cc @gouthamve

**Comment by gouthamve** [comment]
Yep, would love to do it together, but I think it is on the SIG to do the evaluation. Could someone (ideally person driving the evaluation, which is @bwplotka iirc) come back with what you require from the projects for this?

**Comment by bwplotka** [comment]
It's up to SIG (us). 

Ideally (kind of how I think of it) we have to perform review that will allow us to recommend or not the projects based on criteria.
It would be amazing if we can prepare a doc (together with maintainers) with that, but also try to fit in to Due Diligence template: https://github.com/cncf/toc/blob/master/process/dd-review-template.md 

This will ensure (again, in my view), much easier iterations for TOC on Due Diligence step (it is on TOC sponsor). What do you think?

To move things even quicker I think we might consider doing single Due Diligence doc for Cortex and Thanos as most of the things will be the same.. just different in some certain features and customers.

This looks like a good topic for today's call WDYT, @RichiH @halcyondude @gouthamve @povilasv?  https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit#heading=h.z9t2i83su0b3

**Comment by bwplotka** [comment]
Doc: https://docs.google.com/document/d/1jJk5seSUcgwybT4nVGOzaRGrugc90uL3WCY0fUgQh1M/edit

**Comment by povilasv** [comment]
Doc was approved by SIG Observability. Closing the issue, thank you everone!
